### PR TITLE
Feature: server side encryption

### PR DESCRIPTION
**Pull request by justinlboyer**
Added in the ability to include server side encryption on the s3 bucket.
Note: Please test that the code still works when no encryption is required. I was not able to test this.

### CODE REVIEW

**Comment by yaojiach** [comment]
`boto3` does not take `None` for the `ServerSideEncryption` argument. Can you add code to handle when user does not require it?

**Comment by justin-l-boyer** [comment]
@yaojiach What does boto3 take when no encryption is required?  Do you know of a cleaner way to handle this than an if statement that drops the `ServerSideEncryption` key?

**Comment by yaojiach** [comment]
From my understanding of the `botocore` source code, `put_object`'s arguments are directly mapped to parameters of a low-level S3 API call. So if you don't want to use the parameter, you will have to leave it out in the method call.

Using `kwargs` can be more scalable:
```python
def pandas_to_redshift(data_frame,
                       redshift_table_name,
                       column_data_types = None,
                       index = False,
                       save_local = False,
                       delimiter = ',',
                       quotechar = '"',
                       dateformat = 'auto',
                       timeformat = 'auto',
                       region = '',
                       append = False,
                       **kwargs):
    # ...
    accepted_kwargs = ['ServerSideEncryption'] # and other kwargs to accept
    extra_kwargs = {k: v for k, v in kwargs.items() if k in accepted_kwargs and v is not None}
    s3.Bucket(s3_bucket_var).put_object(
        Key= s3_subdirectory_var + csv_name, 
        Body = csv_buffer.getvalue()
        **extra_kwargs  
    )
    # ...
```

**Comment by justinlboyer** [comment]
@yaojiach That's what I thought.  Good thinking.  The file is updated, it'll be a bit until I test it, just fyi.  Thank you for your help, I like how you considered checking for accepted named arguments.

**Pull request merged**
