### PR TITLE
updating core.py to address dask-dataframe types

### PR DESCRIPTION
**Pull request by demousersrccode**
Updated the core.py script to accept data-frames created using the dask library as opposed pandas; update can be found on the d3_to_s3 function

Dask data frames are an alternative to pandas as it allows for parallel processing of data

### CODE REVIEW

**Comment by agawronski** [comment]
@BrightEmah123  I wonder if it makes more sense for you to just fork the whole project, and make it only for dask, literally just make dask-redshift.

Thinking about it more, most people looking for this package are using pandas, esp given that it's in the name, so forcing them to have dask installed to use it seems a bit odd. what do you think @yaojiach ?

**Comment by yaojiach** [comment]
I agree. Or put `dask` into `extras_require` as optional dependency ([doc](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html)).

**Comment by demousersrccode** [comment]
oh ok, I agree with you on this; I think it makes more sense doing that considering the main purpose of this project was to cater for just Pandas Dataframe Types.  I'll do what you requested - fork it and rename it as that. Then I can leave it for you to review.
Thanks.

**Comment by agawronski** [comment]
archiving repository

**Pull request closed without merging**
