### PR TITLE
[wip] infer_dtypes

### PR DESCRIPTION
**Pull request by PabTorre**
A work in progress pull request to talk about the best way to address this change.

### CODE REVIEW

**Comment by PabTorre** [comment]
I think that read_csv method could provide us with the best roadmap on how to handle the inference. 
as this method seemed to resolve all the data type issues I came across, but has the inconvenience of needing to move tables onto csv files or IOStreams first... 

## How is this done on pandas. 

So let's take a look at what they do there taking as an example the parsing of a datestamp. 



1. read_csv uses 
2. _make_parser_function('read_csv', sep=",")  // io/parsers.py(557) 
3. which in turn uses the _read method io/parsers.py(382)
4. _read method uses the TextFileReader  which is a member of class BaseIterator. io/parsers.py(690)
5. after pulling the options and engine settings it goes into CParserWrapper(...) io/parsers(1673)
6. Finally it calls _do_date_convertions method from the ParserBase object. io/parsers.py (1662) 


## What we could do

We should aim at building a BaseIterator to use instead of TextFileReader, that is build for reading the structures we get from RS. So that we are able to use the underlying methods such as the CParserWrapper to do the heavy lifting on Cython. 

To do this, we would need to build build new objects that mirror those of points 2, 3 & 4 above. 

@agawronski

**Comment by agawronski** [comment]
Thank you @PabTorre, I will review this tonight.

**Comment by agawronski** [comment]
Hi @PabTorre, because of the (relative) simplicity of using read_csv directly with an IOStream, I have implemented this idea for testing. If it works well enough, and without performance issue then perhaps this is all we need. We can test this further and determine if we should continue with a more challenging (but potentially much better) method. Let me know what you think!

**Comment by PabTorre** [comment]
It could work.
I have a tendency to go a little too deep and take things apart... so maybe
that does the trick :D

**Comment by agawronski** [comment]
Haha, no! I think going deep is a great idea here. I went through all of the references that you mention in the pandas documentation. I think in the long run, doing this with the method you suggest ("What we could do") is definitely the better idea. I have tested the code I merged to this pr with the [shots log](https://www.kaggle.com/dansbecker/nba-shot-logs/downloads/shot_logs.csv) data, and it seems to work fine, however I do not know what the performance will be on larger datasets. Ultimately I do not think that this solution is ideal, as we already have the data locally as soon as cursor.fetchall() is run, and the current method involves writing to csv (albeit in a buffer) and then calling pd.read_csv() ... I am quite certain that using the method you suggest will perform better. That being said, it might be good to test how this current code performs on larger data, if it is fast enough, then perhaps release a version of pandas_redshift with this feature, and work on improving it with the better method for the next release.

**Comment by agawronski** [comment]
archiving repository

**Pull request closed without merging**
