### PR TITLE
add append change

### PR DESCRIPTION
**Pull request by dfernan**
able to also append data to an existing table

### CODE REVIEW

**Comment by agawronski** [comment]
Thanks @dfernan! I'll take care of the append = True when I get a chance.

**Comment by agawronski** [comment]
I didn't realize that the copy command already appended if the table existed. Thanks!

**Comment by dfernan** [comment]
great thanks! really useful library.

**Comment by agawronski** [comment]
It's update on PyPi now. You should be able to pip install it with your additional changes.

**Comment by dfernan** [comment]
wow this was fast.  I got the new version running and working.. thanks so much!

**Pull request merged**
